igraph/rigraph

R/structural.properties.R

Roxygen header for diameter function

Minor typo in structural.properties.R doc

---

R/structural.properties.R

spelling error in roxygen param for neighborhood

---

R/random_walk.R

'mode' in random_walk should be ignored by undirected

Fix Typo in Doc

---

R/iterators.R

Changing "nuumeric" to "numeric".
I'm fine with GPL 2 or later and FDL.

Fixing small typo

---

R/minimum.spanning.tree.R

Sorry for not contributing something more substantial.

typo in help for minimum.spanning.tree

---

inst/my_html_library.tcl

Update FSF address.

---

R/structural.properties.R

Fixed typo

---

R/structural.properties.R

"breadh-first search" to "breadth-first search"

Correct spelling mistake

---

R/print.R

Noticed with parallel testing.

Fix printing of disconnected edges

---

tests/testthat/test_alpha.centrality.R
tests/testthat/test_clusters.R
tests/testthat/test_indexing.R
tests/testthat/test_indexing2.R
tests/testthat/test_leading.eigenvector.community.R
tests/testthat/test_scan.R

Further cleanup of library() and require() calls

---

.Rbuildignore
.github/workflows/build-and-check.yml
codecov.yml
tools/stimulus/DESCRIPTION

WIP: Add coverage reporting

---

R/attributes.R
R/iterators.R
R/print.R
tests/testthat/test-vs-es.R

chore: extract is_single_index() and get_single_index()

---

R/cliques.R
R/cohesive.blocks.R
R/eulerian.R
R/foreign.R
R/games.R
R/has.R
R/hrg.R
R/layout.R
R/layout_drl.R
R/palette.R
R/plot.R
R/plot.common.R
R/scg.R
tests/testthat/helper.R

chore: Remove or replace `\dontrun{}`

---

R/iterators.R
tests/testthat/test-iterators.R

chore: Iterators over all vertices and edges gain an attribute

---

tests/testthat/_snaps/plot/basic-graph.svg
tests/testthat/test-plot.R
tools/stimulus/DESCRIPTION

The vdiffr package supports easy recording and comparison of visual output. What would be a good set of tests to have before reviewing #157 and #501?

test: Add an example for a plot test

---

R/iterators.R

feat: Support NULL for igraph.vs() and igraph.es()

---

R/iterators.R
R/par.R
R/print.R
man/print.igraph.Rd
man/print.igraph.es.Rd
man/print.igraph.vs.Rd
tests/testthat/_snaps/print.md
tests/testthat/_snaps/vs-es-printing.md
tests/testthat/_snaps/vs-es.md
tests/testthat/test-vs-es-printing.R
tests/testthat/test-vs-es.R
tests/testthat/test_print.R

With stable snapshot tests, for #466.

feat: New id argument to print(), with new option print.id

---

Makefile

fix: Fix builds with some `make` variants

---

.github/workflows/build-and-check.yml
tests/testthat/_snaps/vs-es.md
tests/testthat/test-vs-es.R

I'm having a hard time understanding why this particular test fails. I tried to replicate multiple times. Let's skip for now and monitor.

chore: Stabilize vs-es tests

---

tests/testthat/test_leading.eigenvector.community.R

Fix brittle test

---

README.md

docs: wrap README badges for detection by pkgdown

---

R/print.R

I'm fine with GPL 2 or later and FDL.

docs: clarify print_all() output

---

vignettes/igraph.Rmd

See https://github.com/igraph/rigraph/pull/650#discussion_r1088821998

Rm date field from vignette

---

NEWS.md

docs: fix NEWS.md formatting

---

NEWS.md
R/console.R
cran-comments.md
man/console.Rd
src/core/hrg/hrg.cc

CRAN release v1.4.1

---

R/interface.R
R/zzz-deprecate.R
man/gorder.Rd
man/gsize.Rd

docs: reinstate ecount() and vcount()

---

R/hrg.R
man/fit_hrg.Rd

docs: add docs for as.hclust.igraphHRG()

---

src/rinterface_extra.c

docs: Suggest restarting R session after fatal error

---

src/rinterface.h
src/rinterface_extra.c

in preparation for igraph/C 0.10.
Closes #746.

feat: Avoid longjmp for interrupts

---

src/rinterface.h
src/rinterface_extra.c

https://github.com/igraph/rigraph/pull/750#issuecomment-1493096929

chore: bool and FIXME

---

.Rbuildignore
.github/workflows/build-and-check.yml
DESCRIPTION
NEWS.md
README.md
cran-comments.md
src/rinterface.h
src/rinterface_extra.c
tests/testthat/test-layout.kk.R

CRAN release v1.4.2

---

src/include/igraph_interface.h
src/rinterface.c
src/rinterface_extra.c
tools/stimulus/rinterface.c.in
tools/stimulus/types-RC.yaml

Extracted and adapted from #794.

chore: Prepare for storing igraph object in R structure

---

_pkgdown.yml

To make names on https://r.igraph.org/index.html clickable
Cc @krlmlr

Add authors links to pkgdown config

---

tests/testthat/test-edgenames.R
tests/testthat/test-graph.data.frame.R
tests/testthat/test-igraph.options.R
tests/testthat/test-layout.kk.R
tests/testthat/test-plot.R
tests/testthat/test-print.R

test: Stabilize tests

---

R/basic.R
R/versions.R

chore: Internal refactorings

---

R/versions.R
tests/testthat/_snaps/plot/basic-graph-r-4-2.svg

chore: Refactor and add tests

---

.github/workflows/build-and-check.yml

- add sanitizer step to ci based on https://github.com/krlmlr/rigraph-san docker image

chore: ci sanitizer

---

R/aaa-auto.R
R/motifs.R

chore: Align autogeneration

---

Makefile
Makefile-cigraph

fix: Fix `make clean`

---

.Rbuildignore
.github/workflows/update-citation-cff.yaml
CITATION.cff

Following the docs at https://docs.ropensci.org/cffr/

docs: add cffr file and a GHA workflow that updates it automatically

---

.Rbuildignore
DESCRIPTION
NEWS.md
R/community.R
R/cran.R
cran-comments.md
man/cluster_spinglass.Rd
src/rinterface.h
src/rinterface_extra.c
tests/testthat/helper.R

CRAN release v1.5.1

---

CITATION.cff
R/games.R
man/sample_smallworld.Rd

docs: Update `sample_smallworld()` manual page

---

R/adjacency.R
revdep/README.md
revdep/cran.md
revdep/failures.md
revdep/problems.md
tests/testthat/_snaps/graph.adjacency.md
tests/testthat/test-graph.adjacency.R

feat: Warn if non-symmetric undirected adjacency matrix

---

R/adjacency.R
tests/testthat/_snaps/graph.adjacency.md
tests/testthat/_snaps/par.md
tests/testthat/test-graph.adjacency.R
tests/testthat/test-par.R

Matrices must be truly symmetrical, scalars are accepted.

feat: Improve symmetry check for adjacency matrices on input

---

tests/testthat/test-add.edges.R

test: Stabilize test in preparation for upgrade

---

tests/testthat/test-sample.R

test: Improve test for sampling from Dirichlet distribution

---

R/structural.properties.R
man/bfs.Rd
tests/testthat/_snaps/graph.bfs.md
tests/testthat/test-graph.bfs.R

feat!: `dist` computed by `bfs()` is negative instead of `NaN` for unreachable nodes

---

tests/testthat/test-count.multiple.R

test: Hard-code graph used in test

---

tests/testthat/test-forestfire.R

test: Stabilize `sample_forestfire()` test

---

R/structural.properties.R
man/girth.Rd
tests/testthat/test-girth.R

feat!: `girth()` returns `Inf` for acyclic graphs

---

tests/testthat/test-ba.game.R

Is this a reasonable assumption? Should we run an experiment? (I remember implementing this in my undergrad 🙃 )

test: More robust `sample_pa()` test

---

tests/testthat/test-label.propagation.community.R

test: Stabilize `cluster_label_prop()` test

---

R/random_walk.R
man/random_walk.Rd
tests/testthat/test-random_walk.R

feat!: `random_walk()` adds one more step, the resulting list of vertices is of length `steps + 1`

---

R/interface.R
man/gorder.Rd

https://github.com/mbojan/rgraph6/issues/34#issuecomment-1785377920.

feat!: `vcount()` returns a numeric

---

R/iterators.R

Seems I forgot at least one little thing :sweat_smile:

refactor: use `is_named()` instead of deprecated `is.named()`

---

R/interface.R

Needs to be reverted after the 1.6.0 release.
CC @briatte.

chore: Work around ggnetwork problems for now

---

R/adjacency.R
cran-comments.md
revdep/README.md
revdep/problems.md
tests/testthat/test-graph.adjacency.R

{{{ crp_changes }}}
{{{ check_cran_comments }}}
- Run `fledge::release()`{{{ fledge_gha_workflow_release }}}
- When the package is accepted on CRAN, run `fledge::post_release()`{{{ fledge_gha_workflow_release }}}

CRAN release v1.6.0

---

configure
src/Makevars.in
src/Makevars.ucrt

fix: Fix compilation on Windows with spaces in the Rtools path

---

R/incidence.R
src/cpp11.cpp
src/rinterface_extra.c

For https://github.com/igraph/rigraph/issues/1006.

fix: Fix some deprecated and incompatible pointers warnings

---

tools/deprecate-template.txt
tools/deprecate.R

chore: Add tools script and template for moving to lifecycle

---

src/vendor/io/dl-parser.c

Using
```sh
docker run --rm -ti --platform linux/amd64 -v $(pwd):/root/workspace ghcr.io/cynkra/rig-ubuntu-igraph:main make -f Makefile-cigraph
```

chore: Regenerate parser

---

codecov.yml
src/rinterface.c
tools/stimulus/functions-R.yaml
tools/stimulus/types-RC.yaml
tools/stimulus/types-RR.yaml

refactor: remove unused parts from code generation

---

R/aaa-auto.R
tools/stimulus/types-RC.yaml
tools/stimulus/types-RR.yaml

refactor: clean up some auto-generation code

---

R/aaa-auto.R
R/community.R
R/components.R
R/conversion.R
R/foreign.R
R/structural.properties.R
src/cpp11.cpp
src/rinterface.c
src/rinterface_extra.c
tools/stimulus/types-RC.yaml
tools/stimulus/types-RR.yaml

Makes sure that all enum types are handled as integers  on the R side. This paves the way for eventually auto-generating everything.

chore: Standardize the handling of some stimulus enum types

---

R/centralization.R
man/centr_degree_tmax.Rd

Fix #818
@szhorvat is this what you meant?

feat!: remove default value for 'loops' argument of centr_degree_tmax()

---

R/interface.R
man/get.edge.ids.Rd

feat!: `get.edge.ids(multi = TRUE)` is no longer supported

---

tests/testthat/test-graphNEL.R

identified as I was looking at skipped tests.

test: use specific skip() function

---

R/assortativity.R
man/assortativity.Rd
man/assortativity.nominal.Rd

docs: Add description for `normalized` argument to `assortativity()`

---

CITATION.cff
DESCRIPTION
NEWS.md
R/community.R
R/make.R
R/structural.properties.R
cran-comments.md
man/aaa-igraph-package.Rd
man/communities.Rd
man/k_shortest_paths.Rd
man/realize_degseq.Rd
src/rinterface.c

{{{ crp_changes }}}
{{{ check_cran_comments }}}
- Run `fledge::release()`{{{ fledge_gha_workflow_release }}}
- When the package is accepted on CRAN, run `fledge::post_release()`{{{ fledge_gha_workflow_release }}}

CRAN release v2.0.0

---

CITATION.cff
DESCRIPTION
NEWS.md
R/layout.R
cran-comments.md
man/layout_with_graphopt.Rd

{{{ crp_changes }}}
{{{ check_cran_comments }}}
- Run `fledge::release()`{{{ fledge_gha_workflow_release }}}
- When the package is accepted on CRAN, run `fledge::post_release()`{{{ fledge_gha_workflow_release }}}

CRAN release v2.0.1

---

R/aaa-auto.R
R/components.R
R/lazyeval.R
R/structural.properties.R

fix: Avoid duplicate objects

---

README.md

docs: recommend {pak} instead of {remotes}

---

R/aaa-auto.R
src/rinterface.c
src/vendor/cigraph/CHANGELOG.md
src/vendor/cigraph/interfaces/functions.yaml
src/vendor/cigraph/src/centrality/truss.cpp
src/vendor/cigraph/src/graph/basic_query.c
src/vendor/cigraph/src/graph/type_indexededgelist.c
src/vendor/cigraph/src/paths/all_shortest_paths.c
src/vendor/cigraph/src/paths/sparsifier.c
src/vendor/cigraph/src/properties/trees.c

@krlmlr This includes a cache-related bugfix which should be in the next release.

chore: update C core and regenerate interfaces

---

.github/workflows/build-and-check.yml

Need to investigate more: https://github.com/igraph/rigraph/issues/1311

ci: remove running examples in sanitizer

---

vignettes/igraph.Rmd

object `graph1` has been created and summary is about this new object

docs: Update `igraph.Rmd`, fix manual page typo

---

R/conversion.R
R/games.R
R/hrg.R
man/as_graphnel.Rd
man/fit_hrg.Rd
man/graph_from_graphnel.Rd
man/predict_edges.Rd
man/sample_pref.Rd

docs: replace `\dontrun{}` with `@examplesIf`

---

.github/workflows/build-and-check.yml

Fix: #1334
This steps does more than just installing R, it also sets the library etc.

ci: install R

---

R/attributes.R

still not entirely clear for me

refactor: explaining variables

---

src/rinterface_extra.c

Closes https://github.com/igraph/rigraph/pull/1333.

refactor: handle `null` names for `R_igraph_mybracket2_names`

---

src/rinterface_extra.c

fix: fixed potential memory leak in `R_igraph_community_to_membership2()`

---

tests/testthat/test-assortativity.R

@szhorvat does the name `reference_assortativity()` make sense for that test helper function?

test: refactor test-assortativity for readability

---

tests/testthat/test-operators.R

test: Improve attribute tests

---

tests/testthat/test-bipartite.random.game.R
tests/testthat/test-edge.betweenness.community.R
tests/testthat/test-fastgreedy.community.R
tests/testthat/test-print.R
tests/testthat/test-walktrap.community.R

test: stop using prints_text() in test-bipartite.random.game.R

---

R/make.R

refactor: remove lazyeval usage from R/make.R

---

tests/testthat/test-authority.score.R

see https://github.com/igraph/rigraph/pull/1444#issuecomment-2294824902
is this what you meant @szhorvat?

test: improve HITS test

---

tests/testthat/test-iterators.R

test: add tests for special subsetting functions

---

tests/testthat/test-authority.score.R

What else is needed in this test file?

test: improve hits tests

---

DESCRIPTION
R/make.R
man/make_empty_graph.Rd

docs: add a custom roxygen2 cdocs tag

---

R/adjacency.R
R/conversion.R
R/games.R
R/igraph-package.R
R/layout.R
R/make.R
R/scan.R
man/aaa-igraph-package.Rd
man/as_graphnel.Rd
man/graph.bipartite.Rd
man/graph_from_adjacency_matrix.Rd
man/graph_from_graphnel.Rd
man/graph_from_lcf.Rd
man/layout_as_star.Rd
man/make_bipartite_graph.Rd
man/sample_forestfire.Rd
tools/clean-up-scripts.R

chore: remove references to deprecated functions

---

R/epi.R
R/fit.R

chore: use %||% in R/fit.R

---

CITATION.cff
DESCRIPTION
NEWS.md
R/basic.R
R/centrality.R
R/cliques.R
R/community.R
R/conversion.R
R/games.R
R/interface.R
R/iterators.R
R/layout.R
R/make.R
R/palette.R
R/similarity.R
R/structural.properties.R
cran-comments.md
man/diverging_pal.Rd
man/dot-apply_modifiers.Rd
man/dot-extract_constructor_and_modifiers.Rd
man/dot-igraph.progress.Rd
man/dot-igraph.status.Rd
man/handle_vertex_type_arg.Rd
man/layout_in_circle.Rd
man/sequential_pal.Rd
tests/testthat/test-bug-501-rectangles.R
tests/testthat/test-plot.R

- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)

CRAN release v2.1.0

---

_pkgdown.yml

https://github.com/r-lib/pkgdown/issues/2704

docs: use mathjax for now

---

.Rbuildignore
CITATION.cff
DESCRIPTION
NEWS.md
README.md
cran-comments.md

- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)

CRAN release v2.1.1

---

.github/workflows/build-and-check.yml
tests/testthat/test-plot.R

Don't merge, this PR is just for testing https://github.com/dmurdoch/rgl/issues/439

ci: Install rgl from GitHub for Sanitizer runs

---

R/centrality.R

Minor grammar :bug:

---

R/bipartite.R
R/conversion.R
R/foreign.R
R/operators.R
R/topology.R
man/bipartite_projection.Rd
man/canonical_permutation.Rd
man/complementer.Rd
man/graph_from_adj_list.Rd
man/graph_from_graphdb.Rd
man/permute.Rd
tests/testthat/helper.R
tests/testthat/test-correlated.R
tests/testthat/test-get.adjlist.R
tests/testthat/test-graphNEL.R

chore: Replace `graph.isomorphic()` with `isomorphic()`

---

R/foreign.R
man/graph_from_graphdb.Rd

docs: remove broken example from `graph_from_graphdb()` manual page

---

CITATION.cff
DESCRIPTION
NEWS.md
cran-comments.md

Found the following significant warnings:
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8404:37: warning: ISO C++ forbids flexible array member 'Elements' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8667:22: warning: ISO C++ forbids flexible array member 'pEventLogRecords' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8673:13: warning: ISO C++ forbids flexible array member 'ulOffsets' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/minwindef.h:196:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/minwindef.h:197:3: warning: function declaration isn't …

fledge: CRAN release v2.1.3

---

DESCRIPTION

And add ROR for https://ror.org/02qenvm24

docs: Welcome Maëlle Salmon and David Schoch as authors

---

R/structural-properties.R
man/aaa-igraph-package.Rd
man/distances.Rd

Fix https://github.com/igraph/rigraph/issues/1029
Replaces #1626 that had been reviewed by @szhorvat

docs: better describe output of `all_shortest_paths()`

---

R/make.R
tests/testthat/_snaps/make.md
tests/testthat/test-make.R

 chore: improve `make_empty_graph()` argument checkings

---

tests/testthat/test-incidence.R

Fix #1544
I consider this more than enough now. This function is one of the best tested in the package

test: added more weight tests to `graph_from_biadjacency_matrix()`

---

R/aaa-auto.R
R/interface.R
src/rinterface.c
src/rinterface_extra.c
tools/stimulus/functions-R.yaml

Like #2099 minus the conflicts.

chore: autogenerate `igraph_neighbors()`
