igraph/rigraph

R/plot.common.R
Update curve_multiple function from R/plot.common.R to not generate warnings when processing graphs with loops (self-edges) -- see http://stackoverflow.com/questions/30556493/why-igraph-plot-warns-that-number-of-items-to-replace-is-not-a-multiple-of-repl/30558216#30558216 for the reported bug and the resolution
=> Update curve_multiple to avoid warnings generated for graphs with loops (self-edges)

R/plot.R
`igraph` started printing numbers while plotting one day. It was unexpected.
Is this supposed to be here? Seems like a debugging print that got left behind.
=> Remove strange printing behaviour

R/centrality.R, R/indexing.R
there may also be a typo of similar nature in inst/benchmarks/local.scan.R
=> DOC: typo weight instead of weigth

R/layout.R
adds "in" and "all" to the options so that match.arg does not fall over.
=> Fixes #113 default argument for layout_as_tree

R/layout.R
This is a tiny improvement to the error message given when `layout` is not a valid matrix.
=> add a little more descriptive error message in norm_coords function

.travis.yml, R/community.R, tests/testthat/test_leiden.R, tools/stimulus/init.c
I've added the Leiden algorithm to the R interface. I've also added a simple test.
The `functions.def` did not yet include `igraph_community_leiden` in the `igraph` C core. For that reason the `cigraph` submodule points to [this](https://github.com/igraph/igraph/commit/0bd3384cca577a94fa4c67d27bd7cdde68e6fde6) commit in the `fix/leiden-R` branch for now. If all is well here on the R side as well, we can merge `fix/leiden-R` to the `master` branch, and update the `cigraph` submodule to the `master` branch.
=> Added the Leiden algorithm

inst/README.md
This PR add the current Travis build status to the `README.md`. This not only makes the build status clear, it also makes clear to people that there actually is a CI in the background.
=> Added Travis build status to README.

R/data_frame.R
operatation -> operation
Since this is a typo correction I don't think this patch is copyrightable. But just in case: I'm fine with GPL 2 or later and FDL.
=> Fix minor typo in documentation

Makefile
Existing Makefile did not have any ability to cleanup after itself. The files that are removed come from the exclusions listed in .gitignore (other than printr.R which seems like it shouldn't be there).
This change requires pull request #144 to prevent the current Rd files from being incorrectly deleted.
=> Added support for make clean

tools/uuid/gen_uuid.c
This pull request is for the issue https://github.com/igraph/rigraph/issues/127
This fix will allow us to compile igraph sucessfully on Solaris 11 and SmartOS operating systems
=> Added condition so that SIOCGIFHWADDR block is excluded for SmartOS(Solaris 11)

R/community.R
This addresses the problem that was identified in PR #307. However, instead of interpreting any vector as a suitable membership vector, this PR simply raises a warning if the vector is not numerical.
It would be nice to have "named" communities, so that arbitrary vectors would also be suitable as membership, and that these names would also be consistently used throughout the code base. However, this is a much more extensive change. By allowing this in only a single function (`modularity`), but not elsewhere, this will presumably raise questions. This way, the input is expected to be consistent for all functions, namely a numerical vector.
=> Raise warning if membership is not numerical.

tools/stimulus/rinterface.c.in
This PR fixes #505, and ensures that R does not crash upon interruption. Most relevant details are already discussed in #505, this PR is just to settle on the final details.
I have now included a while loop to ensure that `R_CheckUserInterrupt` will `longjmp`. Without this, I fear that due to some time delays in the GUI that `R_interrupts_suspended` might be set to 1 when we invoke `R_CheckUserInterrupt`, so that it doesn't `longjmp` and just returns. Alternatively, we could include an `IGRAPH_FATAL` call after `R_CheckUserInterrupt`, but that might raise some issues as well. As a final compromise, we could perhaps do a few iterations with `sleep` calls, so that after a few secondS we call `IGRAPH_FATAL`.
=> Fix: correct interruption.

R/layout.R
`layout_nicely()` is the default layout for `plot.igraph`. In most cases, this function calls `layout_with_fr()` for small graphs and `layout_with_drl()` for large ones. Neither of these two support non-positive weights, but they did not validate the weight vector before igraph 1.3.3. Now that they do, `plot(graph)` will fail on graphs with non-positive weights.
This PR makes it so:
- If some weights are not positive, `layout_nicely()` ignores weights with a warning. Thus when using `plot` with default settings, it will not fail.
- `layout_with_fr()` and `layout_with_drl()` continue to throw errors on non-positive weights. When they are used directly and explicitly (instead of through `layout_nicely`), non-positive weights will not be accepted.
- It is not documented that weights must be …
=> Let layout_nicely() accept negative weights

R/interface.R
Add examples to get.edge.ids to demonstrate its behaviour on multiple edges.
=> Add examples to get.edge.ids (multiple edges)

Makefile
This is for avoiding too long lines in `Makevars.win`, for easy review. The assumption is that there is a quoting error, but I don't see it yet.
=> Separate objects by newline in Makevars.win

R/epi.R
Showed up when running examples.
=> Fix warning about partial matching

tests/testthat/test_leading.eigenvector.community.R
The test tested for R > 3.5, and the R version is R 3.5.3 -- so the code ran under that version.
Green builds ftw!
=> test: Skip brittle test on R 3.5 and earlier

tests/testthat/test_leading.eigenvector.community.R
=> fix: Need less-than comparison for test

Makefile, man/as_adj_list.Rd
so that we can run `make docs` before committing, e.g., in a pre-commit hook.
=> chore: Add new docs target to Makefile

R/attributes.R, R/par.R, man/edge_attr-set.Rd, man/edge_attr.Rd, man/set_edge_attr.Rd, man/set_vertex_attr.Rd, man/vertex_attr-set.Rd, man/vertex_attr.Rd
For #466. Two FIXMEs remain, to be addressed in a follow-up PR.
I'd like to propose to make attribute updates a bit stricter as part of this exercise: allow `value` only of length one or the same length as the index. While this is technically a breaking change, most uses of passing `value` of incompatible length are very likely a mistake. @ntamas: What do you think?
=> feat: Support `index = NULL` when setting attributes

patches/002-workaround-gml-creator.patch
We no longer have `IGRAPH_VERSION` available at compile time, and this is the only instance where it is used.
Patching the C core for now. Moving forward, perhaps `igraph_write_graph_gml()` could accept a version argument that can be provided externally?
=> Remove igraph version from GML header

R/plot.R
`rgl` will be deprecating a number of `rgl.*` functions in an upcoming release.  (See https://github.com/dmurdoch/rgl/blob/deprecated/vignettes/deprecation.Rmd for a discussion of the issues.)  This PR does two things:
- It substitutes equivalent `*3d` calls for the `rgl.*` calls.
- It removes workaround code that may have been needed with the `rgl.*` calls, but doesn't appear to be needed now.
=> Use *3d functions rather than rgl.* functions

R/structural.properties.R, man/distances.Rd, src/rinterface.c, tools/stimulus/rinterface.c.in
This PR fixes #571 properly by bringing support for all `mode` values instead of restricting the available modes when `algorithm='johnson'`.
=> distances() with algorithm='johnson' now handles all mode parameter values correctly

R/attributes.R, R/iterators.R, R/par.R, man/edge_attr-set.Rd, man/edge_attr.Rd, man/set_edge_attr.Rd, man/set_vertex_attr.Rd, man/vertex_attr-set.Rd, man/vertex_attr.Rd
Closes #623.
Reverts #607 and #608.
Confirming that it fixes the causaleffect problem.
=> fix: `NULL` means empty vertex or edge list again in all functions

DESCRIPTION, tests/testthat/test-vs-es.R, tests/testthat/test_graph.edgelist.R
for faster parallel testing and to avoid having to skip tests.
The vs-es failures occur sporadically with parallel testing, I hope that they disappear if these tests always run first.
=> Fix test order

.gitignore, revdep/.gitignore, revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md
=> chore: Track revdepcheck results

README.md
@szhorvat would it make sense to retire the wiki page and transfer the content a vignette/article instead so that it'd end up on the pkgdown website (and in the pkgdown search index)?
cc @krlmlr
=> docs: link to installation troubleshooting info

.github/workflows/fledge.yaml
Checks whether the repo is a fork or not. If it's a fork the fledge job will not run.
=> skip fledge job if the repo is a fork

README.md
Since rigraph is on CRAN its universe was automatically created https://igraph.r-universe.dev
For context on R-universe https://ropensci.org/r-universe/
Related issue #658 (the instructions are less useful now for Windows users who wouldn't get a binary from R-universe until that error is fixed).
Note I switched remotes for devtools since devtools is meant to remain the interface for users.
=> docs: Add installation instructions from R-universe

R/igraph-package.R, man/aaa-igraph-package.Rd
so that it doesn't turn up in the local nor pkgdown reference index
=> make package manual page internal

src/core/io/dl-lexer.c, src/core/io/dl-lexer.h, src/core/io/gml-lexer.c, src/core/io/gml-lexer.h, src/core/io/lgl-lexer.c, src/core/io/lgl-lexer.h, src/core/io/ncol-lexer.c, src/core/io/ncol-lexer.h, src/core/io/pajek-lexer.c, src/core/io/pajek-lexer.h, tools/fix-lexers.sh
This attempt to fix the following errors found by CRAN:
https://www.stats.ox.ac.uk/pub/bdr/LTO/igraph.out
```
src/core/io/pajek-lexer.h:500:8: warning: type of ‘igraph_pajek_yyget_leng’ does not match original declaration [-Wlto-type-mismatch]
src/core/io/pajek-lexer.c:2457:11: note: return value type mismatch
src/core/io/pajek-lexer.c:2457:11: note: type ‘yy_size_t’ should match type ‘int’
src/core/io/pajek-lexer.c:2457:11: note: ‘igraph_pajek_yyget_leng’ was previously declared here
src/core/io/pajek-lexer.c:2457:11: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
```
I noticed that this problem does not occur when compiling the C core separately. In fact, it seems that `yyget_leng` _should_ return `int` instead fo `yy_size_t`.
This PR removes the string replacement …
=> fix: fix warning about yyget_leng returning wrong type when using LTO

R/printr.R
A quick fix for errors in `print.igraph` when vertices have very long names.
Closes #675
=> Fix errors when printing long vertex names.

tests/testthat/test-new-layout-api.R
useless now since the package imports it.
=> test: rm leftover magrittr pipe definition

DESCRIPTION
Related to #681
@krlmlr 
I don't think this PR should _close_ the issue since the Remotes field can only be removed after a CRAN release of ape. https://github.com/emmanuelparadis/ape/pull/68#issuecomment-1441266986
=> ci: Fix oldrel runs by adding a dependency on the development version of the ape package

R/iterators.R
- Use correct function (even if it's aliased now)
- Use constant as index into igraph data structure
=> chore: Fix consistency in weakref code

R/conversion.R, tests/testthat/_snaps/graph.data.frame.md, tests/testthat/test-graph.data.frame.R
=> fix: `as_long_data_frame()` now correctly processes vertex attributes and works with graphs without vertex attributes

src/lazyeval.c, src/rinterface.c, src/rinterface_extra.c, src/rrandom.c
to have clean `Rf_` and `R_` prefixes for R API calls.
=> chore: Use `R_NO_REMAP`

src/rinterface.h, src/rinterface_extra.c
This restores the behavior of the current CRAN version. It's also somewhat safe to longjmp if we're not very deep into the call stack.
=> fix: Use longjmp by default in functions called from the top level

tests/testthat/test-graph.bfs.R
Which now correctly distinguishes between NA and NaN. I couldn't compile locally so this is a bit of guess, and you might want to verify with dev waldo yourself.
=> fix: Fix tests for dev waldo

inst/CITATION
Fix #711 
The package whose citation I used as example is GPL-3 licenced https://github.com/cran/lidR/blob/f0dae39007c9d174f6e1962ff236fd8826f1501d/DESCRIPTION#L22
``` r
citation("igraph")
#> 
#> To cite 'igraph' in publications use:
#> 
#>   Csardi G, Nepusz T (2006). "The igraph software package for complex
#>   network research." _InterJournal_, *Complex Systems*, 1695.
#>   <https://igraph.org>.
#> 
#> Csárdi G, Nepusz T, Traag V, Horvát S, Zanini F, Noom D, Müller K
#> (2023). _igraph: Network Analysis and Visualization in R_.
#> doi:10.5281/zenodo.7682609 <https://doi.org/10.5281/zenodo.7682609>, R
#> package version 1.4.99.9002,
#> <https://CRAN.R-project.org/package=igraph>.
#> 
#> To see these entries in BibTeX format, use 'print(<citation>,
#> bibtex=TRUE)', 'toBibtex(.)', or …
```
=> docs: add DOI to CITATION

R/community.R, src/rinterface_extra.c
=> fix: Rename `merges` to `cluster_merges` in output of `cluster_leading_eigen()`

src/rinterface_extra.c
Fixes #811 
- add missed `igraph_vector_destroy` in `R_igraph_restore_pointer` for edges vector
=> fix: The internal `R_igraph_restore_pointer()` no longer leaks memory

DESCRIPTION, src/rinterface_extra.c, tests/testthat/test-handler.R
Only occurs when the igraph package is not attached.
=> fix: Fix handler lookup and protection

vendor/arpack/second.f
The timing function now always returns zero, since we don't need timings for igraph. Fixes #857
=> fix: avoid using of non-standard Fortran function ETIME

R/structural.properties.R, R/zzz-deprecate.R, man/ego.Rd
=> docs: undeprecate neighborhood()

src/rinterface.h, src/rinterface_extra.c, tests/testthat/test-attributes.R, tests/testthat/test-decompose.graph.R
Add a global preserve list to which attribute objects can be added while no corresponding R graph object exists. This list is cleared before the next call to an igraph function.
This will only leak memory if a single igraph function call initializes attributes many times without actually using them, and only before a second igraph function call is made.
The commits can be reviewed individually.
Closes #866.
=> fix: Change ownership rules of attribute objects

src/rinterface_extra.c, tests/testthat/test-attributes.R, tests/testthat/test-constructor-modifiers.R
=> fix: `identical_graphs()` now correctly detects identical graphs without node or edge attributes

tests/testthat/test-dyad.census.R
=> test: Omit test that no longer holds with igraph 0.10

R/structural.properties.R, tests/testthat/test-get.all.shortest.paths.R, tests/testthat/test-get.shortest.paths.R
Are we doing this only because in 0.10 there will be an `edges` component?
=> feat: `all_shortest_paths()` returns the vertex list in both `res` and `vpaths` components

R/trees.R, man/is_tree.Rd, tests/testthat/test-trees.R
=> feat: `is_tree(details = TRUE)` designates the first vertex as root for non-trees

src/rinterface_extra.c
@krlmlr In the interest of making progress and getting 1.6.0 out soon, I propose that for now we just limit interruption checks to every `n`th time. Shall we merge this PR now, and look for better solutions later?
Refs #940, #942
=> fix: Reduce frequency of interruption checks

tests/testthat/test-adjacency.spectral.embedding.R, tests/testthat/test-attributes.R, tests/testthat/test-betweenness.R, tests/testthat/test-bug-154.R, tests/testthat/test-coloring.R, tests/testthat/test-correlated.R, tests/testthat/test-count.multiple.R, tests/testthat/test-dimSelect.R, tests/testthat/test-dot.product.game.R, tests/testthat/test-get.shortest.paths.R, tests/testthat/test-graph.atlas.R, tests/testthat/test-hrg.R, tests/testthat/test-hsbm.R, tests/testthat/test-identical_graphs.R, tests/testthat/test-laplacian.spectral.embedding.R, tests/testthat/test-layout.sugiyama.R, tests/testthat/test-notable.R, tests/testthat/test-operators.R, tests/testthat/test-operators4.R, tests/testthat/test-rewire.R, tests/testthat/test-scan.R, tests/testthat/test-transitivity.R, tools/deprecate-tests.R
=> tests: update based on zzz-deprecate.R

R/plot.shapes.R, tests/testthat/_snaps/bug-501-rectangles/rectangle-edges.svg, tests/testthat/test-bug-501-rectangles.R
Fixes #501.
The `l` matrix here should contain the intersections of edges with the 4 sides of the rectangular node. but due to a typo, one of the intersections was computed incorrectly.
=> fix: Intersections between edges and rectangle vertices are computed correctly

R/aaa-auto.R, tools/stimulus/types-RR.yaml
=> refactor: Replace loop by `lapply()` when returning vertex and edge sets 

R/aaa-auto.R, tools/stimulus/functions-R.yaml
The implementations are currently unused, otherwise tests would be failing.
=> fix: Stimulus argument dependencies

R/structural.properties.R, tests/testthat/test-transitivity.R
Fixes #943. This was also a learning exercise for me after your VERTEX_QTY question, @krlmlr.
=> fix: local (weighted) transitivity now produces a named vector

revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md, src/rinterface.c, src/rinterface.h, src/rinterface_extra.c, tools/stimulus/types-RC.yaml
This is experimental. It is not completely clear to me if calling the error function directly at this point is fine ... there needs to be clarity about `IGRAPH_CHECK` vs `IGRAPH_R_CHECK` and where each is allowed to be used.
This fixes a potential crash in code such as `sample_pref(c(), 3)`. Here `c()` is a zero-length vector which means that the C code would do an out-of-bounds access. This may or may not crash depending on your luck.
The behaviour is now like this:
```
> sample_pref(c(10,20), 3)
Error in sample_pref(c(10, 20), 3) : 
At rinterface.c:1211 : Expecting a scalar but received a vector of length 2. Invalid value
> sample_pref(c(), 3)
Error in sample_pref(c(), 3) : 
At rinterface.c:1211 : Expecting a scalar but received a vector of length 0. Invalid value
```
This is likely to …
=> fix: check that we receive a scalar when expecting a scalar in C code

src/rinterface_extra.c, tests/testthat/test-make_graph.R
This PR adds checks for converting scalars (especially scalar integers) to C in a few heavily used and critical places. This is similar to #1051 but for manually written code. I will not add the checks for all manually written code, only for the most important parts. The rest should be handled by moving functions to auto-generation.
I needed to change a test which verified that `make_graph(NULL, n = NULL)` worked. IMO using `n=NULL` should not be allowed an in fact this probably triggered an invalid memory access, as the code would index into a zero-length vector (which is somehow not caught by the sanitizer). I am not sure why this test was present.
Because of the presence of this unusual test, running revdepchecks would be a good idea.
=> fix: add scalar conversion checks in a few critical places

src/rinterface.h, src/rinterface_extra.c
Fixes #889
This fix is theoretical at the moment. I can't seem to test it on macOS. The test would use a very large amount of memory.
```r
> g<-make_empty_graph(.Machine$integer.max + 2)
> distances(g, v=1)
Error: vector memory exhausted (limit reached?)
```
@krlmlr @Antonov548 Can either of you try to test this on a large-memory Linux machine? I don't have access to one at this moment.  Or otherwise do we merge as-is without a through test?
=> Check that matrix sizes are in the supported range before passing them to R

R/hrg.R, man/hrg_tree.Rd
=> fix: Restore `hrg_tree()` semantics

vignettes/igraph.Rmd, vignettes/igraph_ES.rmd
Random find as I was looking at #1080
=> docs: rm get.adjacency() usage from intro vignettes

src/Makevars.in
I think you may have accidentally copied a wrong version of [src/Makevars.in](https://github.com/igraph/rigraph/blob/main/src/Makevars.in) in #840. What you have now is a broken version of a Windows Makevars, not the unix one.
This PR restores it to the correct version from before #840 plus a small improvement to use the new `sources.mk`.
=> Fixes for Makevars.in for unix (revert accidental file updates) 

tests/testthat/helper-indexing.R, tests/testthat/test-indexing.R, tests/testthat/test-indexing2.R
@szhorvat if `am()` and `mm()` had longer names, what would those be? I'd like to replace them with longer, more informative names.
Removing top-level code in test files help make each test more self-contained, therefore easier to re-run interactively when it fails (as happens in #1080)
Part of #1082
=> test: remove top-level code in test-indexing.R

src/rinterface.c, src/rinterface_extra.c, tools/stimulus/types-RC.yaml
Closes https://github.com/igraph/rigraph/issues/1073
=> fix: remove `R_SEXP_to_hrg` use `R_SEXP_to_hrg_copy` to avoid memory leak

R/interface.R, R/structural.properties.R, man/get.edge.ids.Rd, tests/testthat/test-graph.bfs.R, tests/testthat/test-graph.dfs.R, tests/testthat/test-graphNEL.R
@jefferis: For https://github.com/natverse/nat/issues/517#issuecomment-1902167741.
=> fix: `bfs()` no longer pads `order` with zeros with `igraph_options(return.vs.es = FALSE)`

R/conversion.R, man/as_adjacency_matrix.Rd, man/get.adjacency.Rd, revdep/README.md, revdep/cran.md, revdep/failures.md, revdep/problems.md, tests/testthat/test-indexing.R
For #815, more work needed. Running revdepchecks now.
=> chore!: Hard-deprecate `as_adjacency_matrix(edges = )`

tests/testthat/test-decompose.graph.R
I guess this test didn't need any explicit check, but without one it will be reported as skipped.
=> test: prevent `decompose()` test from being reported as skipped

R/flow.R, man/edge_connectivity.Rd, man/vertex_connectivity.Rd
=> docs: improve Edge connectivity docs

tests/testthat/test-get.incidence.R
Fix #1133 
Will be rebased after #1154 is merged.
The test passes with v1.6.0 too.
=> test: Add `as_biadjacency_matrix()` tests for named vectors

R/aaa-auto.R, R/community.R, R/interface.R, R/layout_drl.R, R/scg.R, cran-comments.md, man/as_membership.Rd, man/cluster_edge_betweenness.Rd, man/cluster_fast_greedy.Rd, man/cluster_fluid_communities.Rd, man/cluster_infomap.Rd, man/cluster_label_prop.Rd, man/cluster_leading_eigen.Rd, man/cluster_leiden.Rd, man/cluster_louvain.Rd, man/cluster_optimal.Rd, man/cluster_spinglass.Rd, man/cluster_walktrap.Rd, man/communities.Rd, man/compare.Rd, man/groups.Rd, man/make_clusters.Rd, man/modularity.igraph.Rd, man/plot_dendrogram.communities.Rd, man/split_join_distance.Rd, src/Makevars.in, src/cpp11.cpp
{{{ crp_changes }}}
{{{ check_cran_comments }}}
- Run `fledge::release()`{{{ fledge_gha_workflow_release }}}
- When the package is accepted on CRAN, run `fledge::post_release()`{{{ fledge_gha_workflow_release }}}
=> CRAN release v2.0.0

R/assortativity.R, man/assortativity.Rd, man/assortativity.nominal.Rd
Fix #1132 
Based on https://igraph.org/c/doc/igraph-Structural.html#igraph_assortativity
@szhorvat is this correct?
=> docs: improve docs of assortativity

src/Makevars.ucrt, src/Makevars.win
Closes https://github.com/igraph/rigraph/issues/1161
=> fix: HAVE_GFORTRAN flag for `win` and `ucrt`

R/structural.properties.R, tests/testthat/test-graph.dfs.R
=> fix: Remove zeros from the `order` and `order.out` components returned by `dfs()`

README.md, vignettes/articles/installation-troubleshooting.Rmd
Since dependencies are no longer optional on Linux, more people are having installation trouble. I tried to improve the readme and troubleshooting instructions to be more helpful. Let's try to get this information online quickly. We can update it later if these dependencies are made optional again.
Ref #1183, https://github.com/igraph/rigraph/issues/490#issuecomment-1915695897
=> docs: improve installation and troubleshooting instructions

R/components.R, man/articulation_points.Rd
=> docs: Fix typo in `?articulation_points`

src/rinterface.c, tools/stimulus/types-RC.yaml
Attempted fix for https://github.com/igraph/rigraph/pull/1173#issuecomment-1925481007
CC @Antonov548, not sure I covered everything.
=> fix: memory leaks when converting data to C

src/vendor/igraph_config.h
@krlmlr Quick workaround for #1189 in the interest of getting the quickfix release out soon.
=> fix: workaround for deprecated enum values not being supported with old GCC

R/structural.properties.R, man/distances.Rd
Whenever I regenerate docs, `RoxygenNote: 7.3.0.9000` in `DESCRIPTION` is changed to `RoxygenNote: 7.3.1`. Can we commit this small version-related change so I don't have keep excluding that file for fear of conflicts?
=> docs: improved docs for shortest path functions

R/aaa-auto.R, src/cpp11.cpp, src/rinterface.c, tools/stimulus/functions-R.yaml
@krlmlr Can we please have this merged now to reduce the pain of having to untangle manual edits to autogenerated files whenever re-running stimulus?
Issues opened:
- https://github.com/igraph/stimulus/issues/6
Explanation of changes:
- `is_bipartite` and `realize_bipartite_degree_sequence` are new in 0.10.9, hence added due to the C core update
- `has_attribute_table` and `igraph_version` were edited to fix a compiler warning, but we don't actually use them, so removed; issue opened in stimulus
- `get_subisomorphisms_vf2_callback`: the generated R code for this was manually removed, and it's simpler to also remove the generated C code until we actually need it.
Ref: #1176
=> refactor: eliminate manual edits from autogenerated files

src/Makevars.ucrt
Fortran libraries (Fortran runtime) is needed e.g. by arpack. This change is to fix building on LLVM/aarch64.
=> fix: Link Fortran runtime on Windows as needed by arpack.

configure
Closes https://github.com/igraph/rigraph/issues/1190
=> fix: `configure` manage libxml multiple include paths

tools/build-requirements.txt
This updates Stimulus to the latest version, fixing issues with generating empty argument lists. See https://github.com/igraph/stimulus/issues/6
Once this version is used to re-generate `rinterface.c`, issues like this will be fixed:
https://github.com/igraph/rigraph/blob/9cc95608d3838149824f3ad44af22fbd6ff60950/src/rinterface.c#L11506-L11507
Please do merge this now but do not re-generate the code until #1207 is merged.
@krlmlr OK to add Stimulus updates to the merge queue myself in the future?
=> chore: update stimulus to 0.21.4

R/topology.R
Closes #1218.
@szhorvat: With this, I'm seeing:
``` r
motif <- igraph::make_empty_graph(directed = FALSE) +
igraph::vertices("D1", "D2", type = c("type1", "type1")) +
igraph::edges("D1", "D2", type = c("type2"))
igraph::subgraph_isomorphisms(
target = motif, pattern = motif, method = "vf2",
vertex.color1 = 2, vertex.color2 = 1
)
#> Error in graph.get.subisomorphisms.vf2(target, pattern, ...): At vendor/cigraph/src/isomorphism/vf2.c:1089 : Invalid vertex color vector length, Invalid value
```
<sup>Created on 2024-02-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
Do you expect this error?
=> fix: `isomorphisms()` and `subgraph_isomorphisims(method = "vf2")` work again, regression introduced in 2.0.0

src/rinterface_extra.c, tests/testthat/test-ba.game.R
Closes #1224.
@krlmlr Let's hope CI passes. Can you please help with adding a test? While this is a stochastic function, `sample_pa(3, out.seq=0:2)` should always output the same thing as `make_full_citation_graph(3)`
=> fix: `sample_pa()` respects the `out.seq` and `out.dist` arguments again, regression introduced in igraph 2.0.0

configure, src/Makevars.in
This PR avoids reliance on the `which` utility, which may not be present on all systems. It addresses complaints like this one: https://github.com/NixOS/nixpkgs/issues/286406
It also renamed `xml2_include_paths` to `lilbxml2_cflags` to better reflect what this variable contains.
=> fix: do not rely on `which` program during configuration

DESCRIPTION, src/Makevars.in, src/Makevars.ucrt, src/Makevars.win, src/vendor/config.h
This is an experiment to see if using the bundled mini-gmp triggers any warnings CRAN would complain about. I noticed that we are already compiling `mini-gmp.c` even though we were not using it.
There are currently no disadvantages to using mini-gmp instead of the full-blown GMP, other than the risk of CRAN demanding source changes to fix warnings. We should not change mini-gmp ourselves it's too risky.
=> refactor: always use bundled mini-gmp

vignettes/igraph.Rmd, vignettes/igraph_ES.rmd
Mostly adding () to function names, removing Latin, styling.
=> docs: formatting tweaks in introductory vignettes

DESCRIPTION, R/operators.R, tests/testthat/_snaps/operators.md, tests/testthat/test-operators.R
Fix  #1231
Partly refactoring for understanding for now.
=> fix: `g + vertices(1, 2, foo = 3)` works again, regression introduced in igraph 2.0.0

R/aaa-auto.R, R/structure.info.R, man/are_adjacent.Rd, src/cpp11.cpp, src/rinterface.c, src/rinterface_extra.c, src/vendor/cigraph/CHANGELOG.md, src/vendor/cigraph/include/igraph_community.h, src/vendor/cigraph/include/igraph_structural.h, src/vendor/cigraph/interfaces/functions.yaml, src/vendor/cigraph/src/CMakeLists.txt, src/vendor/cigraph/src/community/edge_betweenness.c, src/vendor/cigraph/src/connectivity/separators.c, src/vendor/cigraph/src/core/sparsemat.c, src/vendor/cigraph/src/flow/flow.c, src/vendor/cigraph/src/graph/basic_query.c, src/vendor/cigraph/src/io/dl.c, src/vendor/cigraph/src/io/gml.c, src/vendor/cigraph/src/io/lgl.c, src/vendor/cigraph/src/io/ncol.c, src/vendor/cigraph/src/io/pajek.c, src/vendor/cigraph/src/misc/matching.c, src/vendor/cigraph/src/operators/compose.c, src/vendor/cigraph/src/operators/disjoint_union.c, src/vendor/cigraph/src/operators/rewire.c, src/vendor/cigraph/src/operators/subgraph.c, src/vendor/cigraph/src/paths/sparsifier.c, tests/testthat/test-are_adjacent.R, tools/stimulus/functions-R.yaml
=> refactor: auto-generate `are_adjacent()`, avoid deprecated `igraph_are_connected()` C function

src/rinterface_extra.c, tests/testthat/_snaps/old-data-type.md, tests/testthat/_snaps/versions.md
I tried to work with some old saved graphs and encountered the error message:
```
Error in warn_version(graph) : 
This graph was created by a now unsupported old igraph version.
Call upgrade_version() before using igraph functions on that object.
```
However, there is no `upgrade_version()` function exported by the `igraph` package, but there is an `upgrade_graph()` function which correctly upgrades the old objects.  This pull requests just modifies the incorrect error message (and the test results which expect the error output).
=> docs: Fix error messages mentioning to mention `upgrade_graph()` instead of the nonexisting `upgrade_version()`

R/flow.R, man/is_min_separator.Rd, man/is_separator.Rd
See https://github.com/igraph/igraph/pull/2509 as well.
=> docs: remove incorrect claim about handling of complete graphs by `is_separator()` and `is_min_separator()`

R/plot.R, tests/testthat/test-plot.R
Fix #25
I do not understand the code, but this apparently fixes the bug and follows the pattern of the previous code lines. :innocent:
=> fix: Fix `rglplot(edge_label = )`

_pkgdown.yml
@szhorvat which version do you prefer, link above under links or in a separate section? In the screenshot below I am showing both options at once.
=> docs: add link to discussion forum

R/flow.R, man/min_st_separators.Rd, tests/testthat/_snaps/minimal.st.separators.md, tests/testthat/test-minimal.st.separators.R
@maelle Is this the best way to comment on examples? Can we comment using normal text that includes math instead of writing code comments? If yes, can you push to this branch and demonstrate?
=> docs: Improve `min_st_separators()` documentation

DESCRIPTION, configure, src/Makevars.ucrt, src/Makevars.win, src/vendor/config.h
Closes https://github.com/igraph/rigraph/issues/1217
=> chore: make libxml optional

.github/workflows/build-and-check.yml, tools/run_examples.R
Closes: https://github.com/igraph/rigraph/issues/1195
Proof that it detects memory leaks in examples: https://github.com/igraph/rigraph/pull/1286
=> ci: run examples with sanitizer

R/centrality.R, man/strength.Rd
=> docs: remove misleading comment about warning given as no warning is given

R/conversion.R, man/as.directed.Rd
=> docs: make `x11()` usage in example happen only in interactive sessions

.github/workflows/lock.yaml
Closes #1258.
@igraph/core-team @igraph/developers: When this is merged, your GH notifications might get flooded. Apologies, happy to arrange a time when it's good to merge.
=> chore: Install lock workflow to lock stale discussions after one year

.github/workflows/lock.yaml
- There were two warnings on https://github.com/igraph/rigraph/actions/runs/8335586645
- The docs of the action show V5, the permissions field. https://github.com/dessant/lock-threads?tab=readme-ov-file#examples
=> ci: Update lock.yaml

tests/testthat/test-plot.R
The `rgl` package is a `Suggests` dependency. As such, testing of functions depending on `rgl` should skip if it is not installed. This PR adds such a skip condition.
Test failures due to lack of skip condition were encountered during [Conda Forge builds of v2.0.3](https://github.com/conda-forge/r-igraph-feedstock/pull/59).
=> test: Add skip condition for `rglplot` test

R/adjacency.R, man/graph_from_adjacency_matrix.Rd
Fix #1290
@clpippel does this look good? Thanks a lot for your help!
=> docs: fix `graph_from_adjacency_matrix()` examples to avoid warnings

R/games.R, man/sample_degseq.Rd
fix #1289 
- renamed variables, added explaining variables for clarity.
- conditionally use withr, to make sure it works.
note that `rlang::check_installed()` will prompt the user to install withr, which is handy IMHO.
=> docs: fix `sample_degseq()` example

R/games.R, man/sample_forestfire.Rd, tests/testthat/test-forestfire.R
Fix #1292
- test: refactor sample_forestfire() tests to make them smaller and more self-contained
- docs: simplify example to not have to deal with log of 0
=> sample_forestfire() tests and example :fire:

tests/testthat/test-clusters.R, tests/testthat/test-degseq.R, tests/testthat/test-diameter.R, tests/testthat/test-edge.connectivity.R
Thanks @szhorvat for telling me about `largest_component()`.
=> test: use largest_component() and expect_equal() in test files

R/attributes.R, tests/testthat/test-attributes.R
=> refactor: add assert_named_list() helper to assert the value is a named list with no duplicate names

tools/run_examples.R
Closes https://github.com/igraph/rigraph/issues/1199
=> ci: run examples with comment `\dontrun{}`

R/foreign.R, tests/testthat/test-read_graph.R
Fixes #1346
I'm sorry, I really don't have time for a test, but I hope someone can add one based on my first comment in #1346.
=> fix: fix reading of LGL and NCOL files (broken in 2.0.0)

R/games.R, R/make.R, man/degree.sequence.game.Rd, man/make_.Rd, man/sample_degseq.Rd, tests/testthat/test-games.R
Fix  #876
See @szhorvat, a new feature exposed after all the boring refactoring PRs. :grin: :innocent: Some questions
- where do the numbers corresponding to the method come from? I assumed the new one was 4.
- what could be a better test for the new method?
=> feat: rename sample_degseq() method and add the edge.switching.simple method

R/community.R, man/cluster_leiden.Rd, tests/testthat/test-leiden.R
Fixes #883. I've only updated the R file and the test, all the rest should follow automatically, if my understanding is correct? If more is needed, let me know.
=> Rename resolution_parameter to resolution

R/games.R, tests/testthat/test-games.R
=> fix: `sample_degseq()` works with old method names again

tests/testthat/helper.R
Fix #1331
Not ready yet, it needs a few PRs to be merged first (as `expect_that()` is still used on main, but will be useless after those PRs):
=> test: remove expect_that() definition

R/operators.R, tests/testthat/test-operators.R
Fix #761
Including commits refactoring the test file before I added the test. :innocent:
=> fix: remove unintended type conversions when using `disjoint_union()`

R/structural.properties.R, man/laplacian_matrix.Rd
=> docs: improve documentation of normalization methods for laplacian_matrix()

.github/CONTRIBUTING.md
Fix #1422
cf https://github.com/igraph/rigraph/pull/1421#issuecomment-2203002998
The `CONTRIBUTING.md` guide is where R developers would expect to find these things, especially as pkgdown will link to the file automatically.
=> docs: add slightly tweaked boilerplate CONTRIBUTING.md

R/make.R
This is the fix for BCT, at least it fixes the reprex :grin: 
I'm a bit worried about these functions we inlined, looking forward to deprecating the old versions for good so we don't have to backport all changes. :cold_sweat: 
``` r
s <- c("2", "11", "00", "10", "12", "011", "020", "021", "012", "022", 
"0100", "0102", "0101") 
init_g <- igraph::make_empty_graph(n=1)
igraph::V(init_g)$name <-""
g <- init_g
for (word in c(s)) {
print(word)
subwords <- stringr::str_sub(word, 1, 1:nchar(word))
subg <- igraph::graph.lattice(length(subwords)+1,directed=TRUE)
igraph::V(subg)$name <- c("",subwords)
g <- igraph::union(g, subg)
}
#> [1] "2"
#> Warning: `graph.lattice()` was deprecated in igraph 2.0.4.
#> ℹ Please use `make_lattice()` instead.
#> This warning is displayed once every 8 hours.
#> …
```
=> fix: Align the body of `graph.lattice()` with its replacement `make_lattice()`

R/fit.R, man/fit_power_law.Rd, src/cpp11.cpp, src/rinterface_extra.c
=> feat: Support `fit_power_law(implementation = "plfit.p")` to compute the P-value

R/flow.R, man/is_separator.Rd
=> docs: update is_separator() documentation based on C docs

R/make.R, man/graph_from_atlas.Rd, man/graph_from_edgelist.Rd, man/graph_from_literal.Rd, man/make_.Rd, man/make_chordal_ring.Rd, man/make_empty_graph.Rd, man/make_full_citation_graph.Rd, man/make_full_graph.Rd, man/make_graph.Rd, man/make_lattice.Rd, man/make_ring.Rd, man/make_star.Rd, man/make_tree.Rd, man/roxygen/meta.R, man/simplified.Rd, man/with_edge_.Rd, man/with_graph_.Rd, man/with_vertex_.Rd, man/without_attr.Rd, man/without_loops.Rd, man/without_multiples.Rd
Fix #1417
To me making `make_()` part of both families has no real downside, it'll be easier to maintain the cross-links this way, and the text in the rest of the manual page is clear enough.
=> docs: improve cross-links from make_() manual page

R/conversion.R, src/rinterface_extra.c
Fixes #1429
This does fix the issue reported in #1429, and is ready to go right now in that sense. But you may want to polish it up to prepare the ground for future improvements.  I leave it in your hands @Antonov548 @krlmlr 
You may also want to add some tests (weighted and unweighted undirected case).
=> fix: fix includig diagonal elements in dense adjacency matrices

R/plot.shapes.R
=> chore: add some argument checking to `add_shape()`

R/iterators.R, man/inside-square-error.Rd
=> fix: add ellipsis to dummy functions `.nei()` and others

R/make.R
=> chore: soft-deprecate `graph_()`

R/aaa-auto.R, tools/stimulus/types-RR.yaml
=> chore: replace `is.directed()` with `is_directed()` in stimulus YAML

R/games.R, man/erdos.renyi.game.Rd, tests/testthat/test-adjacency.spectral.embedding.R, tests/testthat/test-correlated.R, tests/testthat/test-laplacian.spectral.embedding.R, tests/testthat/test-scan.R, tests/testthat/test-sgm.R
=> lifecycle: `erdos.renyi.game()` and `random.graph.game()` soft deprecation

src/vendor/cigraph/CHANGELOG.md, src/vendor/cigraph/src/layout/large_graph.c, src/vendor/igraph_version.h
This is to bring the fix https://github.com/igraph/igraph/issues/2676 to R.
CC @maelle 
I'm going ahead with adding the mergequeue label, as this is a single fix that shouldn't break packages if the introduction of the bug in R/igraph 2.0 didn't. Let me know if you prefer I don't do this in the future @krlmlr.
=> chore: Update vendored sources to igraph/igraph@1f153e9ca1b7e03ae4387d2500b4ccf4d3bc2703

R/incidence.R, tests/testthat/_snaps/incidence.md, tests/testthat/test-incidence.R
Also characterization tests as prep for #1518
=> test: add tests for `graph_from_biadjacency_matrix()`

R/conversion.R, man/as.undirected.Rd
=> fix: preserve `as.undirected()` signature thanks to @jhollway

README.md
Fix #1239
But I think not all contributors are detected.
=> docs: update allcontributors table

src/Makevars.ucrt
Some upcoming version of Rtools will ship with libxml2 which will depend on bcrypt. This patch updates linking on Windows for that. Also, the patch conditionally uses pkg-config (when available, which it is in current version of Rtools) to establish the dependencies so that such upgrades in the future should not require changes in the package.
=> Prepare for libxml2 depending on bcrypt, use pkg-config.

.gitignore, R/fit.R, man/fit_power_law.Rd, src/cpp11.cpp, src/rinterface_extra.c, tests/testthat/test-fit.R
…led in `fit_power_law()` with the plfit method
This PR is to help make quicker progress on #1158. It is not finished: a decision must be made on the interface of requesting a p-value calculation. Please see https://github.com/igraph/rigraph/issues/1158#issuecomment-2393117859
Can someone please take this over from here?
=> feat: Add `p.value` and `p.precision` arguments to `fit_power_law()` to control the computation of the p-value

R/motifs.R, man/graph.motifs.est.Rd, man/sample_motifs.Rd, tests/testthat/test-motifs.R, tests/testthat/test-plot.R
@krlmlr Please use this fix instead of the one in #1565, which doesn't seem correct. This also fixes a bad default value for the `sample.size` parameter. Recent igraph errors for non-integer values.
=> fix: fix the incorrect handling of the `sample` parameter in `sample_motifs()` and ensure that the default `sample.size` is integer

igraph.Rproj
@moodymudskipper: This works for igraph to use devtag (and another roclet) in the standard "Document" menu command.
Do we want a blog post or an entry in the README? And `use_devtag()` could take care of that?
=> chore: Configure the RStudio IDE to use the extra roclets

DESCRIPTION, NEWS.md, cran-comments.md
Found the following significant warnings:
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8404:37: warning: ISO C++ forbids flexible array member 'Elements' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8667:22: warning: ISO C++ forbids flexible array member 'pEventLogRecords' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8673:13: warning: ISO C++ forbids flexible array member 'ulOffsets' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/minwindef.h:196:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/minwindef.h:197:3: warning: function declaration isn't …
=> fledge: CRAN pre-release v2.1.1.9900

R/interface.R
fixes #1605
The problem is that in `adjacent_vertices()`, 1 is only added to the vertices if `return.vs.es` is `TRUE`.
=> fix: `adjacent_vertices()` and `incident_edges()` are now correct if the `"return.vs.es"` option is `FALSE`

CITATION.cff, R/interface.R, tests/testthat/test-get.adjlist.R, tests/testthat/test-interface.R
This completes the fix of #1605 and adds tests.
Since the tests of `neighbors()` were based on `as_adj_list()`, I have extended the test of the latter to also run with `return.vs.es = FALSE`. I extended the tests of `neighbors()` and added tests for `adjacent_vertices()` and `incident_edges()`.
I found another small issue related to this one that I think is a mistake. But I am not entirely sure that it is, so I would like to have confirmation before I fix it: `as_adj_edge_list()` does not respect the setting `return.vs.es` and always returns `igraph.es` objects. Could someone please confirm that this is indeed not the expected behaviour. I could then fix this and update the pull request. Or should I open a new issue for this?
=> test: Test handling of `"return.vs.es"` in several functions

CITATION.cff, DESCRIPTION, NEWS.md, cran-comments.md
Found the following significant warnings:
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8404:37: warning: ISO C++ forbids flexible array member 'Elements' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8667:22: warning: ISO C++ forbids flexible array member 'pEventLogRecords' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8673:13: warning: ISO C++ forbids flexible array member 'ulOffsets' [-Wpedantic]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/minwindef.h:196:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/minwindef.h:197:3: warning: function declaration isn't …
=> fledge: CRAN release v2.1.2

README.md, _pkgdown.yml
"Use lifecycle for all experimental functions, make a central note in the documentation." is part of the R Consortium proposal. 
Have we missed functions that should have the experimental badge? If so, how could I identify them?
Local preview:
=> docs: add central note about experimental functions

.Rbuildignore, R/operators.R, igraph.Rproj, man/closeness.Rd, man/disjoint_union.Rd
=> docs: Make documentation of `disjoint_union()` consistent with behavior

src/rinterface.h, src/rinterface_extra.c
=> feat: Use safe accessor to vector elements

.github/workflows/R-CMD-check.yaml, .github/workflows/each.yaml
For branches that start with `each-`, each commit is checked. Useful for checking how vendoring affects build and check results, commit by commit.
=> ci: Add workflow to check each commit

R/layout.R, tests/testthat/_snaps/layout.md, tests/testthat/test-layout.R
…with_kk()` and `layout_with_fr()`
Fix #1108
This does not remove them completely yet but since they're in the lifecycle system, and we plan to advance deprecation over time, we can then close the issue.
@krlmlr could you please run revdeps on this? Thank you!
=> chore!: stricter deprecation of non-functional parameters of `layout_with_kk()` and `layout_with_fr()`

R/aaa-auto.R, src/rinterface.c, src/rinterface_extra.c, tools/stimulus/functions-R.yaml, tools/stimulus/types-RC.yaml
This PR contains two changes:
- General cleanup in the auto-generated code
- Adapt to changed in this PR on the C side: https://github.com/igraph/igraph/pull/2690
Both PRs should be merged at the same time.
There is some duplicate NULL-check ugliness that is not harmful, but should be cleaned up. I think this needs to be fixed directly in Stimulus. Can you help with this @Antonov548 ?  Example: `(Rf_isNull(weights) ? 0 : (Rf_isNull(weights) ? NULL : &c_weights))`
I'm marking this as draft so it doesn't get accidentally merged before we all agree, but from my side it's good to go.
=> chore: Adapt handling of optional parameters to interface definition changes in the C core

R/indexing.R, tests/testthat/test-indexing2.R
This PR refactors single bracket manipulating of a graph (`g[1:3,4:6] <- 2`) (#1465). 
The only real change is the use of `get_edge_ids` instead of the old `[.igraph` to get edge ids which makes the function more readable, slightly faster and a lower memory footprint.
Fixes an unintended behaviour (fix #1662)
=> fix!: Subset assignment of a graph avoids addition of double edges and ignores loops unless the new `loops` argument is set to `TRUE`

R/conversion.R, tests/testthat/_snaps/conversion.md, tests/testthat/test-conversion.R
This PR removes (nested) for loops for `get.adjacency.dense()` when `attr != NULL`
(cherry picked commits from #1518)
=> refactor: forward `get.adjacency.dense()` to `get.adjacency.sparse()` if attributes are present (#1483)

R/interface.R, tests/testthat/_snaps/interface.md, tests/testthat/test-interface.R
Also for `add_edges()` ?
The matrix case works already by accident, a two-row matrix will give the intended result. Should we soft-deprecate the matrix case to later support two-column matrices?
``` r
set.seed(20250120)
g <- sample_gnp(20, 0.1)
g
#> IGRAPH dc0368b U--- 20 22 -- Erdos-Renyi (gnp) graph
#> + attr: name (g/c), type (g/c), loops (g/l), p (g/n)
#> + edges from dc0368b:
#>  [1]  1-- 3  1-- 5  3-- 8  7-- 8  5--11 10--11  2--12  3--14  5--14  1--15
#> [11] 10--15 11--15  4--16  6--16 12--16  1--17 15--17  3--18  4--18  8--19
#> [21] 11--19 12--19
x <- c(1, 3, 1, 5, 3, 8)
get_edge_ids(g, x)
#> [1] 1 2 3
m <- matrix(x, nrow = 2)
m
#>      [,1] [,2] [,3]
#> [1,]    1    1    3
#> [2,]    3    5    8
get_edge_ids(g, m)
#> [1] 1 2 3
```
<sup>Created on 2025-01-20 with …
=> feat: `get_edge_ids()` accepts data frames and matrices

R/indexing.R, tests/testthat/test-indexing.R
This PR refactors single bracket querying of a graph (`g[1:3,4:6]`) (closes #1465). 
In the old version, the complete adjacency matrix was computed and then a subset created. The refactored function now builds the submatrix directly. This leads to a little speedup and a lower memory footprint.
``` r
set.seed(411)
g <- sample_gnp(5000,0.1)
bench::mark(
check = FALSE,
new = igraph:::get_adjacency_submatrix(g,1:100,1:100),
old = as_adjacency_matrix(g)[1:100,1:100]
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 new          1.84ms   1.94ms    452.      4.26MB     24.0
#> 2 old         61.36ms 118.39ms …
```
=> perf: Faster single bracket querying of a graph

R/adjacency.R, tests/testthat/test-adjacency.R
This PR is a large refactoring of `graph.adjacency.sparse()`. The goal was to make the function more readable and remove some performance bottlenecks. 
The only cases that has a slightly worse performance in some cases are `mode = "min"` and `mode = "max"` (However, there are some fluctuations I do not fully understand). The new implementation is a simple one-liner. Probably needs some discussions.
``` r
packageVersion("igraph")
#> [1] '2.1.3'
A <- sample_gnp(5000,0.02, directed = FALSE) |> as_adjacency_matrix()
bench::mark(
check = FALSE,
old = igraph:::graph.adjacency.sparse(A,mode = "undirected"),
new = graph.adjacency.sparse.new(A,mode = "undirected")
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#> …
```
=> refactor:  enhance readability and performance of graph.adjacency.sparse

R/incidence.R, tests/testthat/_snaps/incidence.md
~~This PR removes (nested) for loops for `graph.incidence.dense()` when `weighted = TRUE`~~
~~(cherry picked commits from https://github.com/igraph/rigraph/pull/1518)~~
This PR removes `graph.incidence.sparse()` and `graph.incidence.dense()` and replaces it with a general `graph.incidence.build()` and more specialized helper functions.
=> refactor: consolidate graph.incidence.* (#1483)

CONTRIBUTING.md
=> docs: add more about igraph.r2cdocs in the contributing guide

R/hrg.R, tests/testthat/_snaps/hrg.md, tests/testthat/test-hrg.R
Fix #1074
@szhorvat for info I could only find two functions with HRG as input (well there are methods but methods don't need to check the class if I follow correctly)
=> feat: hrg functions check their argument

R/plot.common.R
fix #293 
Replaces NA values in attributes used for plotting with the default value and shows a warning
``` r
schema <- make_empty_graph() + vertices("c", "p1", "p2", color = "green", shape = "rectangle", 
size = 30, size2 = 30) + vertices("d", shape = "circle")
as_data_frame(schema,"vertices")
#>    name color     shape size size2
#> c     c green rectangle   30    30
#> p1   p1 green rectangle   30    30
#> p2   p2 green rectangle   30    30
#> d     d  <NA>    circle   NA    NA
plot(schema)
#> Warning: vertex attribute size contains NAs. Replacing with default value 15
#> Warning: vertex attribute color contains NAs. Replacing with default value 1
#> Warning: vertex attribute size contains NAs. Replacing with default value 15
#> Warning: vertex attribute size2 contains …
```
=> fix: NA attribute values are replaced with default values for plotting

R/plot.R, tests/testthat/_snaps/plot/loop-graph.svg, tests/testthat/test-plot.R
Fix #157
``` r
g <- make_graph(c(1, 2, 1, 1, 2, 3), directed = F)
cols <- c('red','green','blue')
plot(g, edge.color = cols, edge.label.color = cols, edge.label = cols)
```
Also fixed font, family and cex
=> fix: correct mapping of edge label properties in plots when loops are present

R/plot.R
Fix #640 
``` r
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
plot( 
make_tree(4),
edge.arrow.mode=1,
edge.color=rgb(0,0,0,0.2)
)
```
``` r
plot( 
make_tree(4),
edge.arrow.mode=2,
edge.color=rgb(0,0,0,0.2)
)
```
``` r
plot( 
make_tree(4),
edge.arrow.mode=3,
edge.color=rgb(0,0,0,0.2)
)
```
<sup>Created on 2025-02-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
=> fix: Duplicated arrowhead drawing

R/plot.common.R
=> refactor: one less tmp use case

R/plot.common.R
tests on ubuntu 22.04 (4.0) fail otherwise
=> fix: use function instead of \(x) in arrow.mode

R/iterators.R, tests/testthat/_snaps/iterators.md, tests/testthat/test-iterators.R
Fix #848 
Did not remove recycling for length 1 vectors because that still makes sense in my opinion
``` r
pkgload::load_all("~/git/R_packages/rigraph/")
#> ℹ Loading igraph
g <- make_ring(5)
V(g)[c(TRUE, FALSE)]
#> Error in `FUN()`:
#> ! Error: Logical index length does not match the number of vertices.
#>   Recycling is not allowed.
E(g)[c(TRUE, FALSE)]
#> Error in `FUN()`:
#> ! Error: Logical index length does not match the number of edges.
#>   Recycling is not allowed.
V(g)[TRUE]
#> + 5/5 vertices, from bafeef3:
#> [1] 1 2 3 4 5
E(g)[FALSE]
#> + 0/5 edges from bafeef3:
```
<sup>Created on 2025-03-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
=> fix: Recycling of logical vectors when indexing into edge/vertex selectors now throws an error

R/foreign.R, man/graph_from_graphdb.Rd, tests/testthat/_snaps/foreign.md, tests/testthat/test-foreign.R
Fix #1712
Downloaded the database from here: https://zenodo.org/records/11204020
and hosted it here: https://github.com/schochastics/graphsdb/
General question: should we host it somewhere else?
=> fix: changed base location for graph_from_graphdb and added tests

.github/pull_request_template.md
See https://github.com/igraph/igraph/pull/2720
This is meant to apply to external contributors. Team members should feel free to delete the text when opening PRs.
=> chore: require copyright assignment in PR template

src/rinterface_extra.c
Effects of this change:
- Fixes #1434 and eliminates a potential way to crash igraph
- Potential small performance penalty. Probably inconsequential, but not measured.
- This can potentially trigger an UBSan warning, and that's okay. The warning will only be triggered when passing invalid values. If this happens, the test suite or examples should be changed.
- Values that were in the past blindly rounded are now checked. May cause revdepcheck failures.
=> fix: integer vectors are validated before transferring them to the C library

R/structural-properties.R
This PR makes the necessary doc updates after this C core PR: https://github.com/igraph/igraph/pull/2720
Merge this only after:
=> docs: update decription of `order` parameter of `ego()` and related functions

DESCRIPTION, R/similarity.R, man/similarity.Rd
This makes the test-similarity.R test pass again.
Do you agree on the way I added the new parameters? We can't put them at the same place as in the C core, since that would break existing code that relies on argument position rather than argument name.
Relevant lines in the C changelog:
>  - `igraph_similarity_jaccard()` and `igraph_similarity_dice()` now take two sets of vertices to create vertex pairs of, instead of one.
PR in the C core: https://github.com/igraph/igraph/pull/2346
I haven't found the documentation for this in the C core, which could mean I didn't search properly.
=> feat: new arguments `vids_from` and `vids_to` for `similarity()`

R/aaa-auto.R, R/paths.R, src/rinterface.c, src/vendor/cigraph/interfaces/functions.yaml, tools/stimulus/functions-R.yaml
@szhorvat this works as it makes two current failures disappear (from the "next"/"b-next" branches) but I'd like your advice on whether the changes I made should live in the stimulus config file instead. For later today if we have time!
=> chore: account for changes in weighted eccentricity+radius
